version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: backend/dockerfile
    ports:
      - "8000:8000"
    environment:
      - RAGFLOW_API_KEY=${RAGFLOW_API_KEY}
      - RAGFLOW_BASE_URL=${RAGFLOW_BASE_URL}
      - RAGFLOW_CHAT_ID=${RAGFLOW_CHAT_ID}
    volumes:
      - ./chat_history.db:/app/chat_history.db
      - ./logs:/var/log/app
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge